var Module={};fetch("https://raw.githubusercontent.com/Noxturnix/assyst-nxcrypt/main/nxencrypt.wasm").then(r=>r.arrayBuffer()).then(rw=>{Module.wasmBinary=rw;var h;h||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},h),ba="./this.program",ca="object"==typeof window,r="function"==typeof importScripts,w="",da,x;
var ha=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.thisProgram&&(ba=h.thisProgram);var ia;h.wasmBinary&&(ia=h.wasmBinary);"object"!=typeof WebAssembly&&ja("no native wasm support detected");var ka,la=!1,y,z,A,ma,C,D,na,oa,pa=[],qa=[],ra=[];function sa(){var a=h.preRun.shift();pa.unshift(a)}var F=0,ta=null,G=null;function ja(a){h.onAbort?.(a);a="Aborted("+a+")";ha(a);la=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
function wa(a){var b=new Uint8Array(ia);b=new WebAssembly.Module(b);return[new WebAssembly.Instance(b,a),b]}
var xa=a=>{for(;0<a.length;)a.shift()(h)},ya="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,I=(a,b)=>{var c=z,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&ya)return ya.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var g=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var l=c[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|l:(e&7)<<18|g<<12|l<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=
String.fromCharCode(e)}return d};class za{constructor(a){this.P=a-24}}
var Aa=0,Ba=0,Ca,J=a=>{for(var b="";z[a];)b+=Ca[z[a++]];return b},K={},L={},Da={},M,Ea=a=>{throw new M(a);},N,Q=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new N("Mismatched type converter count");for(var m=0;m<a.length;++m)O(a[m],k[m])}a.forEach(function(k){Da[k]=b});var e=Array(b.length),g=[],l=0;b.forEach((k,m)=>{L.hasOwnProperty(k)?e[m]=L[k]:(g.push(k),K.hasOwnProperty(k)||(K[k]=[]),K[k].push(()=>{e[m]=L[k];++l;l===g.length&&d(e)}))});0===g.length&&d(e)};
function Fa(a,b,c={}){var d=b.name;if(!a)throw new M(`type "${d}" must have a positive integer typeid pointer`);if(L.hasOwnProperty(a)){if(c.ya)return;throw new M(`Cannot register type '${d}' twice`);}L[a]=b;delete Da[a];K.hasOwnProperty(a)&&(b=K[a],delete K[a],b.forEach(e=>e()))}function O(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return Fa(a,b,c)}
var Ga=a=>{throw new M(a.G.R.O.name+" instance already deleted");},Ha=!1,Ia=()=>{},Ja=(a,b,c)=>{if(b===c)return a;if(void 0===c.U)return null;a=Ja(a,b,c.U);return null===a?null:c.va(a)},Ka={},R=[],La=()=>{for(;R.length;){var a=R.pop();a.G.da=!1;a["delete"]()}},S,T={},Ma=(a,b)=>{if(void 0===b)throw new M("ptr should not be undefined");for(;a.U;)b=a.ga(b),a=a.U;return T[b]},Na=(a,b)=>{if(!b.R||!b.P)throw new N("makeClassHandle requires ptr and ptrType");if(!!b.V!==!!b.S)throw new N("Both smartPtrType and smartPtr must be specified");
b.count={value:1};return U(Object.create(a,{G:{value:b,writable:!0}}))},U=a=>{if("undefined"===typeof FinalizationRegistry)return U=b=>b,a;Ha=new FinalizationRegistry(b=>{b=b.G;--b.count.value;0===b.count.value&&(b.S?b.V.Z(b.S):b.R.O.Z(b.P))});U=b=>{var c=b.G;c.S&&Ha.register(b,{G:c},b);return b};Ia=b=>{Ha.unregister(b)};return U(a)};function Oa(){}
var Pa=(a,b)=>Object.defineProperty(b,"name",{value:a}),Qa=(a,b,c)=>{if(void 0===a[b].T){var d=a[b];a[b]=function(){if(!a[b].T.hasOwnProperty(arguments.length))throw new M(`Function '${c}' called with an invalid number of arguments (${arguments.length}) - expects one of (${a[b].T})!`);return a[b].T[arguments.length].apply(this,arguments)};a[b].T=[];a[b].T[d.ha]=d}},Ra=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].T&&void 0!==h[a].T[c])throw new M(`Cannot register public name '${a}' twice`);
Qa(h,a,a);if(h.hasOwnProperty(c))throw new M(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);h[a].T[c]=b}else h[a]=b,void 0!==c&&(h[a].Ja=c)},Sa=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Ta(a,b,c,d,e,g,l,k){this.name=a;this.constructor=b;this.ea=c;this.Z=d;this.U=e;this.wa=g;this.ga=l;this.va=k;this.Aa=[]}
var Ua=(a,b,c)=>{for(;b!==c;){if(!b.ga)throw new M(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ga(a);b=b.U}return a};function Va(a,b){if(null===b){if(this.ma)throw new M(`null is not a valid ${this.name}`);return 0}if(!b.G)throw new M(`Cannot pass "${Wa(b)}" as a ${this.name}`);if(!b.G.P)throw new M(`Cannot pass deleted object as a pointer of type ${this.name}`);return Ua(b.G.P,b.G.R.O,this.O)}
function Xa(a,b){if(null===b){if(this.ma)throw new M(`null is not a valid ${this.name}`);if(this.ja){var c=this.Ba();null!==a&&a.push(this.Z,c);return c}return 0}if(!b||!b.G)throw new M(`Cannot pass "${Wa(b)}" as a ${this.name}`);if(!b.G.P)throw new M(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ia&&b.G.R.ia)throw new M(`Cannot convert argument of type ${b.G.V?b.G.V.name:b.G.R.name} to parameter type ${this.name}`);c=Ua(b.G.P,b.G.R.O,this.O);if(this.ja){if(void 0===b.G.S)throw new M("Passing raw pointer to smart pointer is illegal");
switch(this.Da){case 0:if(b.G.V===this)c=b.G.S;else throw new M(`Cannot convert argument of type ${b.G.V?b.G.V.name:b.G.R.name} to parameter type ${this.name}`);break;case 1:c=b.G.S;break;case 2:if(b.G.V===this)c=b.G.S;else{var d=b.clone();c=this.Ca(c,Ya(()=>d["delete"]()));null!==a&&a.push(this.Z,c)}break;default:throw new M("Unsupporting sharing policy");}}return c}
function Za(a,b){if(null===b){if(this.ma)throw new M(`null is not a valid ${this.name}`);return 0}if(!b.G)throw new M(`Cannot pass "${Wa(b)}" as a ${this.name}`);if(!b.G.P)throw new M(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.G.R.ia)throw new M(`Cannot convert argument of type ${b.G.R.name} to parameter type ${this.name}`);return Ua(b.G.P,b.G.R.O,this.O)}function $a(a){return this.fromWireType(D[a>>2])}
function ab(a,b,c,d,e,g,l,k,m,n,p){this.name=a;this.O=b;this.ma=c;this.ia=d;this.ja=e;this.za=g;this.Da=l;this.sa=k;this.Ba=m;this.Ca=n;this.Z=p;e||void 0!==b.U?this.toWireType=Xa:(this.toWireType=d?Va:Za,this.W=null)}
var bb=(a,b,c)=>{if(!h.hasOwnProperty(a))throw new N("Replacing nonexistant public symbol");void 0!==h[a].T&&void 0!==c?h[a].T[c]=b:(h[a]=b,h[a].ha=c)},cb=[],db,eb=a=>{var b=cb[a];b||(a>=cb.length&&(cb.length=a+1),cb[a]=b=db.get(a));return b},fb=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=h["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=eb(b).apply(null,c);return d}},V=(a,b)=>{a=J(a);var c=a.includes("j")?fb(a,b):
eb(b);if("function"!=typeof c)throw new M(`unknown function pointer with signature ${a}: ${b}`);return c},gb,ib=a=>{a=hb(a);var b=J(a);W(a);return b},jb=(a,b)=>{function c(g){e[g]||L[g]||(Da[g]?Da[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new gb(`${a}: `+d.map(ib).join([", "]));},kb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c},lb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function nb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].W)return!0;return!1}function ob(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Pa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function pb(a,b,c,d,e,g){var l=b.length;if(2>l)throw new M("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,m=nb(b);c="void"!==b[0].name;d=[a,Ea,d,e,lb,b[0],b[1]];for(e=0;e<l-2;++e)d.push(b[e+2]);if(!m)for(e=k?1:2;e<b.length;++e)null!==b[e].W&&d.push(b[e].W);m=nb(b);e=b.length;var n="",p="";for(l=0;l<e-2;++l)n+=(0!==l?", ":"")+"arg"+l,p+=(0!==l?", ":"")+"arg"+l+"Wired";n=`\n        return function (${n}) {\n        if (arguments.length !== ${e-
2}) {\n          throwBindingError('function ' + humanName + ' called with ' + arguments.length + ' arguments, expected ${e-2}');\n        }`;m&&(n+="var destructors = [];\n");var u=m?"destructors":"null",v="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");k&&(n+="var thisWired = classParam['toWireType']("+u+", this);\n");for(l=0;l<e-2;++l)n+="var arg"+l+"Wired = argType"+l+"['toWireType']("+u+", arg"+l+");\n",v.push("argType"+l);k&&(p="thisWired"+(0<p.length?", ":
"")+p);n+=(c||g?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(m)n+="runDestructors(destructors);\n";else for(l=k?1:2;l<b.length;++l)g=1===l?"thisWired":"arg"+(l-2)+"Wired",null!==b[l].W&&(n+=g+"_dtor("+g+");\n",v.push(g+"_dtor"));c&&(n+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [f,q]=[v,n+"}\n"];f.push(q);b=ob(f).apply(null,d);return Pa(a,b)}var qb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a};
class rb{constructor(){this.Y=[void 0];this.oa=[]}get(a){return this.Y[a]}has(a){return void 0!==this.Y[a]}}var Y=new rb,sb=a=>{a>=Y.pa&&0===--Y.get(a).ta&&(Y.Y[a]=void 0,Y.oa.push(a))},Ya=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:a={ta:1,value:a};var b=Y.oa.pop()||Y.Y.length;Y.Y[b]=a;return b}};function tb(a){return this.fromWireType(C[a>>2])}
var ub={name:"emscripten::val",fromWireType:a=>{if(!a)throw new M("Cannot use deleted val. handle = "+a);var b=Y.get(a).value;sb(a);return b},toWireType:(a,b)=>Ya(b),argPackAdvance:8,readValueFromPointer:tb,W:null},Wa=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},vb=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(na[c>>2])};case 8:return function(c){return this.fromWireType(oa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);
}},wb=(a,b,c)=>{switch(b){case 1:return c?d=>y[d>>0]:d=>z[d>>0];case 2:return c?d=>A[d>>1]:d=>ma[d>>1];case 4:return c?d=>C[d>>2]:d=>D[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},xb=(a,b,c,d)=>{if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var l=a.charCodeAt(++e);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+
3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}},yb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},zb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Ab=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ma[c];)++c;c<<=1;if(32<c-a&&zb)return zb.decode(z.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=A[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},
Bb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)A[b>>1]=a.charCodeAt(e),b+=2;A[b>>1]=0;return b-d},Cb=a=>2*a.length,Db=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Eb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var l=a.charCodeAt(++e);
g=65536+((g&1023)<<10)|l&1023}C[b>>2]=g;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d},Fb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Gb={},Ib=()=>{if(!Hb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in Gb)void 0===Gb[b]?delete a[b]:a[b]=Gb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);
Hb=c}return Hb},Hb,Jb=a=>0===a%4&&(0!==a%100||0===a%400),Kb=[31,29,31,30,31,30,31,31,30,31,30,31],Lb=[31,28,31,30,31,30,31,31,30,31,30,31];function Mb(a){var b=Array(yb(a)+1);xb(a,b,0,b.length);return b}
for(var Nb=(a,b,c,d)=>{function e(f,q,t){for(f="number"==typeof f?f.toString():f||"";f.length<q;)f=t[0]+f;return f}function g(f,q){return e(f,q,"0")}function l(f,q){function t(P){return 0>P?-1:0<P?1:0}var B;0===(B=t(f.getFullYear()-q.getFullYear()))&&0===(B=t(f.getMonth()-q.getMonth()))&&(B=t(f.getDate()-q.getDate()));return B}function k(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function m(f){var q=f.aa;for(f=new Date((new Date(f.ba+1900,0,1)).getTime());0<q;){var t=f.getMonth(),B=(Jb(f.getFullYear())?Kb:Lb)[t];if(q>B-f.getDate())q-=B-f.getDate()+1,f.setDate(1),11>t?f.setMonth(t+1):(f.setMonth(0),f.setFullYear(f.getFullYear()+1));else{f.setDate(f.getDate()+q);break}}t=new Date(f.getFullYear()+1,0,4);q=k(new Date(f.getFullYear(),
0,4));t=k(t);return 0>=l(q,f)?0>=l(t,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var n=D[d+40>>2];d={Ga:C[d>>2],Fa:C[d+4>>2],ka:C[d+8>>2],na:C[d+12>>2],la:C[d+16>>2],ba:C[d+20>>2],X:C[d+24>>2],aa:C[d+28>>2],Ka:C[d+32>>2],Ea:C[d+36>>2],Ha:n?n?I(n):"":""};c=c?I(c):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y",
"%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in n)c=c.replace(new RegExp(p,"g"),n[p]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),v="January February March April May June July August September October November December".split(" ");n={"%a":f=>u[f.X].substring(0,3),"%A":f=>u[f.X],"%b":f=>v[f.la].substring(0,3),"%B":f=>v[f.la],"%C":f=>g((f.ba+1900)/100|0,2),"%d":f=>
g(f.na,2),"%e":f=>e(f.na,2," "),"%g":f=>m(f).toString().substring(2),"%G":m,"%H":f=>g(f.ka,2),"%I":f=>{f=f.ka;0==f?f=12:12<f&&(f-=12);return g(f,2)},"%j":f=>{for(var q=0,t=0;t<=f.la-1;q+=(Jb(f.ba+1900)?Kb:Lb)[t++]);return g(f.na+q,3)},"%m":f=>g(f.la+1,2),"%M":f=>g(f.Fa,2),"%n":()=>"\n","%p":f=>0<=f.ka&&12>f.ka?"AM":"PM","%S":f=>g(f.Ga,2),"%t":()=>"\t","%u":f=>f.X||7,"%U":f=>g(Math.floor((f.aa+7-f.X)/7),2),"%V":f=>{var q=Math.floor((f.aa+7-(f.X+6)%7)/7);2>=(f.X+371-f.aa-2)%7&&q++;if(q)53==q&&(t=(f.X+
371-f.aa)%7,4==t||3==t&&Jb(f.ba)||(q=1));else{q=52;var t=(f.X+7-f.aa-1)%7;(4==t||5==t&&Jb(f.ba%400-1))&&q++}return g(q,2)},"%w":f=>f.X,"%W":f=>g(Math.floor((f.aa+7-(f.X+6)%7)/7),2),"%y":f=>(f.ba+1900).toString().substring(2),"%Y":f=>f.ba+1900,"%z":f=>{f=f.Ea;var q=0<=f;f=Math.abs(f)/60;return(q?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":f=>f.Ha,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(p in n)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),n[p](d)));c=c.replace(/\0\0/g,"%");p=Mb(c);
if(p.length>b)return 0;y.set(p,a);return p.length-1},Ob=Array(256),Pb=0;256>Pb;++Pb)Ob[Pb]=String.fromCharCode(Pb);Ca=Ob;M=h.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};N=h.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};
Object.assign(Oa.prototype,{isAliasOf:function(a){if(!(this instanceof Oa&&a instanceof Oa))return!1;var b=this.G.R.O,c=this.G.P;a.G=a.G;var d=a.G.R.O;for(a=a.G.P;b.U;)c=b.ga(c),b=b.U;for(;d.U;)a=d.ga(a),d=d.U;return b===d&&c===a},clone:function(){this.G.P||Ga(this);if(this.G.fa)return this.G.count.value+=1,this;var a=U,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.G;a=a(c.call(b,d,{G:{value:{count:e.count,da:e.da,fa:e.fa,P:e.P,R:e.R,S:e.S,V:e.V}}}));a.G.count.value+=1;a.G.da=!1;return a},
["delete"](){this.G.P||Ga(this);if(this.G.da&&!this.G.fa)throw new M("Object already scheduled for deletion");Ia(this);var a=this.G;--a.count.value;0===a.count.value&&(a.S?a.V.Z(a.S):a.R.O.Z(a.P));this.G.fa||(this.G.S=void 0,this.G.P=void 0)},isDeleted:function(){return!this.G.P},deleteLater:function(){this.G.P||Ga(this);if(this.G.da&&!this.G.fa)throw new M("Object already scheduled for deletion");R.push(this);1===R.length&&S&&S(La);this.G.da=!0;return this}});h.getInheritedInstanceCount=()=>Object.keys(T).length;
h.getLiveInheritedInstances=()=>{var a=[],b;for(b in T)T.hasOwnProperty(b)&&a.push(T[b]);return a};h.flushPendingDeletes=La;h.setDelayFunction=a=>{S=a;R.length&&S&&S(La)};
Object.assign(ab.prototype,{xa(a){this.sa&&(a=this.sa(a));return a},ra(a){this.Z?.(a)},argPackAdvance:8,readValueFromPointer:$a,fromWireType:function(a){function b(){return this.ja?Na(this.O.ea,{R:this.za,P:c,V:this,S:a}):Na(this.O.ea,{R:this,P:a})}var c=this.xa(a);if(!c)return this.ra(a),null;var d=Ma(this.O,c);if(void 0!==d){if(0===d.G.count.value)return d.G.P=c,d.G.S=a,d.clone();d=d.clone();this.ra(a);return d}d=this.O.wa(c);d=Ka[d];if(!d)return b.call(this);d=this.ia?d.ua:d.pointerType;var e=
Ja(c,this.O,d.O);return null===e?b.call(this):this.ja?Na(d.O.ea,{R:d,P:e,V:this,S:a}):Na(d.O.ea,{R:d,P:e})}});gb=h.UnboundTypeError=((a,b)=>{var c=Pa(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);return c})(Error,"UnboundTypeError");
Y.Y.push({value:void 0},{value:null},{value:!0},{value:!1});Object.assign(Y,{pa:Y.Y.length});h.count_emval_handles=()=>{for(var a=0,b=Y.pa;b<Y.Y.length;++b)void 0!==Y.Y[b]&&++a;return a};
var Rb={g:(a,b,c,d)=>{ja(`Assertion failed: ${a?I(a):""}, at: `+[b?b?I(b):"":"unknown filename",c,d?d?I(d):"":"unknown function"])},f:(a,b,c)=>{var d=new za(a);D[d.P+16>>2]=0;D[d.P+4>>2]=b;D[d.P+8>>2]=c;Aa=a;Ba++;throw Aa;},n:()=>{},x:(a,b,c,d)=>{b=J(b);O(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(z[e])},W:null})},z:(a,b,c,d,e,g,l,k,m,n,p,u,v)=>{p=J(p);g=V(e,g);k&&=V(l,k);n&&=V(m,n);
v=V(u,v);var f=Sa(p);Ra(f,function(){jb(`Cannot construct ${p} due to unbound types`,[d])});Q([a,b,c],d?[d]:[],function(q){q=q[0];if(d){var t=q.O;var B=t.ea}else B=Oa.prototype;q=Pa(p,function(){if(Object.getPrototypeOf(this)!==P)throw new M("Use 'new' to construct "+p);if(void 0===E.$)throw new M(p+" has no accessible constructor");var mb=E.$[arguments.length];if(void 0===mb)throw new M(`Tried to invoke ctor of ${p} with invalid number of parameters (${arguments.length}) - expected (${Object.keys(E.$).toString()}) parameters instead!`);
return mb.apply(this,arguments)});var P=Object.create(B,{constructor:{value:q}});q.prototype=P;var E=new Ta(p,q,P,v,t,g,k,n);if(E.U){var X;(X=E.U).qa??(X.qa=[]);E.U.qa.push(E)}t=new ab(p,E,!0,!1,!1);X=new ab(p+"*",E,!1,!1,!1);B=new ab(p+" const*",E,!1,!0,!1);Ka[a]={pointerType:X,ua:B};bb(f,q);return[t,X,B]})},t:(a,b,c,d,e,g)=>{var l=kb(b,c);e=V(d,e);Q([],[a],function(k){k=k[0];var m=`constructor ${k.name}`;void 0===k.O.$&&(k.O.$=[]);if(void 0!==k.O.$[b-1])throw new M(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.O.$[b-1]=()=>{jb(`Cannot construct ${k.name} due to unbound types`,l)};Q([],l,n=>{n.splice(1,0,null);k.O.$[b-1]=pb(m,n,null,e,g);return[]});return[]})},c:(a,b,c,d,e,g,l,k,m)=>{var n=kb(c,d);b=J(b);b=qb(b);g=V(e,g);Q([],[a],function(p){function u(){jb(`Cannot call ${v} due to unbound types`,n)}p=p[0];var v=`${p.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&
p.O.Aa.push(b);var f=p.O.ea,q=f[b];void 0===q||void 0===q.T&&q.className!==p.name&&q.ha===c-2?(u.ha=c-2,u.className=p.name,f[b]=u):(Qa(f,b,v),f[b].T[c-2]=u);Q([],n,function(t){t=pb(v,t,p,g,l,m);void 0===f[b].T?(t.ha=c-2,f[b]=t):f[b].T[c-2]=t;return[]});return[]})},w:a=>O(a,ub),i:(a,b,c)=>{b=J(b);O(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:vb(b,c),W:null})},h:(a,b,c,d,e,g,l)=>{var k=kb(b,c);a=J(a);a=qb(a);e=V(d,e);Ra(a,function(){jb(`Cannot call ${a} due to unbound types`,
k)},b-1);Q([],k,function(m){m=[m[0],null].concat(m.slice(1));bb(a,pb(a,m,null,e,g,l),b-1);return[]})},b:(a,b,c,d,e)=>{b=J(b);-1===e&&(e=4294967295);e=k=>k;if(0===d){var g=32-8*c;e=k=>k<<g>>>g}var l=b.includes("unsigned")?function(k,m){return m>>>0}:function(k,m){return m};O(a,{name:b,fromWireType:e,toWireType:l,argPackAdvance:8,readValueFromPointer:wb(b,c,0!==d),W:null})},a:(a,b,c)=>{function d(g){return new e(y.buffer,D[g+4>>2],D[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array][b];c=J(c);O(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ya:!0})},j:(a,b)=>{b=J(b);var c="std::string"===b;O(a,{name:b,fromWireType:function(d){var e=D[d>>2],g=d+4;if(c)for(var l=g,k=0;k<=e;++k){var m=g+k;if(k==e||0==z[m]){l=l?I(l,m-l):"";if(void 0===n)var n=l;else n+=String.fromCharCode(0),n+=l;l=m+1}}else{n=Array(e);for(k=0;k<e;++k)n[k]=String.fromCharCode(z[g+k]);n=n.join("")}W(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&
(e=new Uint8Array(e));var g="string"==typeof e;if(!(g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new M("Cannot pass non-string to std::string");var l=c&&g?yb(e):e.length;var k=Qb(4+l+1),m=k+4;D[k>>2]=l;if(c&&g)xb(e,z,m,l+1);else if(g)for(g=0;g<l;++g){var n=e.charCodeAt(g);if(255<n)throw W(m),new M("String has UTF-16 code units that do not fit in 8 bits");z[m+g]=n}else for(g=0;g<l;++g)z[m+g]=e[g];null!==d&&d.push(W,k);return k},argPackAdvance:8,readValueFromPointer:$a,
W(d){W(d)}})},e:(a,b,c)=>{c=J(c);if(2===b){var d=Ab;var e=Bb;var g=Cb;var l=()=>ma;var k=1}else 4===b&&(d=Db,e=Eb,g=Fb,l=()=>D,k=2);O(a,{name:c,fromWireType:m=>{for(var n=D[m>>2],p=l(),u,v=m+4,f=0;f<=n;++f){var q=m+4+f*b;if(f==n||0==p[q>>k])v=d(v,q-v),void 0===u?u=v:(u+=String.fromCharCode(0),u+=v),v=q+b}W(m);return u},toWireType:(m,n)=>{if("string"!=typeof n)throw new M(`Cannot pass non-string to C++ string type ${c}`);var p=g(n),u=Qb(4+p+b);D[u>>2]=p>>k;e(n,u+4,p+b);null!==m&&m.push(W,u);return u},
argPackAdvance:8,readValueFromPointer:tb,W(m){W(m)}})},y:(a,b)=>{b=J(b);O(a,{Ia:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},r:()=>1,l:sb,m:a=>{4<a&&(Y.get(a).ta+=1)},k:(a,b)=>{var c=L[a];if(void 0===c)throw a="_emval_take_value has unknown type "+ib(a),new M(a);a=c;a=a.readValueFromPointer(b);return Ya(a)},d:()=>{ja("")},s:()=>Date.now(),v:(a,b,c)=>z.copyWithin(a,b,b+c),u:()=>{ja("OOM")},p:(a,b)=>{var c=0;Ib().forEach((d,e)=>{var g=b+c;e=D[a+4*e>>2]=g;for(g=0;g<d.length;++g)y[e++>>
0]=d.charCodeAt(g);y[e>>0]=0;c+=d.length+1});return 0},q:(a,b)=>{var c=Ib();D[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);D[b>>2]=d;return 0},o:(a,b,c,d)=>Nb(a,b,c,d)},Z=function(){function a(c){Z=c.exports;ka=Z.A;c=ka.buffer;h.HEAP8=y=new Int8Array(c);h.HEAP16=A=new Int16Array(c);h.HEAPU8=z=new Uint8Array(c);h.HEAPU16=ma=new Uint16Array(c);h.HEAP32=C=new Int32Array(c);h.HEAPU32=D=new Uint32Array(c);h.HEAPF32=na=new Float32Array(c);h.HEAPF64=oa=new Float64Array(c);db=Z.D;qa.unshift(Z.B);F--;
h.monitorRunDependencies?.(F);0==F&&(null!==ta&&(clearInterval(ta),ta=null),G&&(c=G,G=null,c()));return Z}var b={a:Rb};F++;h.monitorRunDependencies?.(F);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return ha(`Module.instantiateWasm callback failed with error: ${c}`),!1}b=wa(b);return a(b[0])}(),Qb=Z.C,W=Z.E,hb=Z.F;h.dynCall_iijii=Z.H;h.dynCall_iiijiji=Z.I;h.dynCall_iiijiii=Z.J;h.dynCall_viijii=Z.K;h.dynCall_iiiiij=Z.L;h.dynCall_iiiiijj=Z.M;h.dynCall_iiiiiijj=Z.N;h.run=Sb;var Tb;
G=function Ub(){Tb||Sb();Tb||(G=Ub)};
function Sb(){function a(){if(!Tb&&(Tb=!0,h.calledRun=!0,!la)){xa(qa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();ra.unshift(b)}xa(ra)}}if(!(0<F)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)sa();xa(pa);0<F||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();Sb();let av=new Module.VecStr();args.forEach(e=>av.push_back(e)); let o=Module.run(av);av.delete();return o})
